- id: pypfmt
  name: pypfmt
  description: Sort and format pyproject.toml files
  entry: pypfmt
  language: python
  files: (^|/)pyproject\.toml$
  args: []
  require_serial: false
  minimum_pre_commit_version: "3.2.0"
